/*
 * EDG_MEM_ADDR.h
 *
 *  Created on: 11/04/2023
 *      Author: Elkin Granados
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef EDG_MEM_ADDR_H_
#define EDG_MEM_ADDR_H_

#ifdef __cplusplus
extern "C" {
#endif

/* Definiciones para seleccionar el IDE	-------------------------------------*/

#define EDG_MEM_ADDR_BASE					(0x0000U)
#define	EDG_MEM_ADDR_OFFSET					(0x0010)

#define EDG_MEM_ADDR_PROGRAM_QTY			(10U)
#define EDG_MEM_ADDR_POS_X_PROGRAM_VALUE	(1U)
#define EDG_MEM_ADDR_VALUES_X_PROGRAM		(6U)
#define EDG_MEM_ADDR_PROGRAM_OFFSET			(EDG_MEM_ADDR_POS_X_PROGRAM_VALUE * EDG_MEM_ADDR_VALUES_X_PROGRAM)
#define EDG_MEM_ADDR_PROGRAM_TOTAL_SIZE		(EDG_MEM_ADDR_PROGRAM_QTY * EDG_MEM_ADDR_PROGRAM_OFFSET)

#define EDG_MEM_ADDR_SCHEDULE_QTY			(7U)
#define EDG_MEM_ADDR_POS_X_SCHEDULE_VALUE	(1U)
#define EDG_MEM_ADDR_VALUES_X_SCHEDULE		(8U)
#define EDG_MEM_ADDR_SCHEDULE_OFFSET		(EDG_MEM_ADDR_POS_X_SCHEDULE_VALUE * EDG_MEM_ADDR_VALUES_X_SCHEDULE)
#define EDG_MEM_ADDR_SCHEDULE_TOTAL_SIZE	(EDG_MEM_ADDR_SCHEDULE_QTY * EDG_MEM_ADDR_SCHEDULE_OFFSET)

#define EDG_MEM_ADDR_OFFSET_QTY				(6U)
#define EDG_MEM_ADDR_POS_X_OFFSET_VALUE		(1U)
#define EDG_MEM_ADDR_VALUES_X_OFFSET		(1U)
#define EDG_MEM_ADDR_OFFSET_OFFSET			(EDG_MEM_ADDR_VALUES_X_OFFSET * EDG_MEM_ADDR_POS_X_OFFSET_VALUE)
#define EDG_MEM_ADDR_OFFSET_TOTAL_SIZE		(EDG_MEM_ADDR_OFFSET_QTY *EDG_MEM_ADDR_OFFSET_OFFSET)

#define EDG_MEM_ADDR_BASE_PROGRAM			(EDG_MEM_ADDR_BASE)
#define EDG_MEM_ADDR_BASE_SCHEDULE			(EDG_MEM_ADDR_BASE_PROGRAM + EDG_MEM_ADDR_PROGRAM_TOTAL_SIZE + EDG_MEM_ADDR_OFFSET)
#define EDG_MEM_ADDR_BASE_OFFSET			(EDG_MEM_ADDR_BASE_SCHEDULE + EDG_MEM_ADDR_SCHEDULE_TOTAL_SIZE + EDG_MEM_ADDR_OFFSET)

#ifdef __cplusplus
}
#endif

#endif /* EDG_MEM_ADDR_H_ */
